"""Onboarding, registration, and source management."""

from __future__ import annotations

import contextlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import typer

from turnzero.cli.base import (
    HTTP_OK,
    _data_dir,
    console,
    err_console,
)

source_app = typer.Typer(
    help="Enable or disable Expert Prior sources (local/community/team).",
    no_args_is_help=True,
)


def _generate_hook(python_path: str, data_dir: Path) -> str:
    return f'''\
#!/usr/bin/env python3
"""TurnZero UserPromptSubmit hook — auto-inject Expert Priors at Turn 0.

Generated by `turnzero setup`. Re-run `turnzero setup --force` to regenerate.
Fires on every user message but only injects on the first turn of a session.
Silent on any error or timeout.
"""
from __future__ import annotations

import json, os, signal, sys
from pathlib import Path

DATA_DIR = Path("{data_dir}")
MIN_PROMPT_LEN = 15
TIMEOUT_SECS = 5

def _bail(_signum=None, _frame=None): sys.exit(0)
signal.signal(signal.SIGALRM, _bail)
signal.alarm(TIMEOUT_SECS)

try:
    # 1. Detect Turn 0
    data = json.loads(sys.stdin.read())
    transcript = data.get("transcript", [])
    if any(m.get("role") == "assistant" for m in transcript):
        sys.exit(0)

    prompt = data.get("prompt", "").strip()
    if len(prompt) < MIN_PROMPT_LEN:
        sys.exit(0)

    # 2. Query Expert Priors
    os.environ["TURNZERO_DATA_DIR"] = str(DATA_DIR)
    from turnzero.blocks import load_all_blocks
    from turnzero.retrieval import load_index, query as _query

    blocks = load_all_blocks(DATA_DIR / "blocks")
    index = load_index(DATA_DIR / "index.jsonl")

    # Match retrieval.py DEFAULT_THRESHOLD
    results = _query(prompt, index, blocks, top_k=3, threshold=0.70, context_weight=4000, strict_intent=True)
    if not results:
        sys.exit(0)

    # 3. Output for Claude Code injection
    names = " · ".join(b.slug for b, _ in results)
    print(f"[TurnZero] Auto-injecting {{len(results)}} Expert Prior(s): {{names}}\\n")
    for block, _score in results:
        print(block.to_injection_text())
        print()

    print(
        "INSTRUCTION: You have been given Expert Priors above by TurnZero. "
        "Start your response with exactly one line acknowledging them, formatted as:\\n"
        f"  > 📎 TurnZero applied: {{names}}\\n"
        "Then continue with your normal response. Do not explain what TurnZero is."
    )
except Exception:
    sys.exit(0)
'''


_TURNZERO_CLAUDE_MD_BLOCK = """\

## TurnZero — Expert & Personal Prior Injection
TurnZero MCP is installed. Follow these rules to establish a consistent **Portable AI Identity** and domain-specific grounding:

### 1. Context Injection (Turn 0)
- **Rule:** ALWAYS call `list_suggested_blocks` before responding to ANY non-trivial user message.
- **Why:** This retrieves your **Personal Priors** (Always-On Identity) and relevant **Expert Priors** (Domain Knowledge).
- **Skip:** Only skip for pure chitchat (greetings, one-word replies).

### 2. Creating Priors (`submit_candidate`)
- **Expert Priors (`is_personal=False`):** Use this for general technical truth, library "gotchas," or domain-specific rules (e.g., "SQLAlchemy 2.0 requires select()"). These are for the community.
- **Personal Priors (`is_personal=True`):** Use this for the user's idiosyncratic preferences, personal style, or specific project quirks (e.g., "I prefer 2-space indents," "Be extremely concise"). These are private.
- **Confidence:** Always set `auto_approve=True` for live session corrections.

### 3. Session Management (`reset_session`)
- **Rule:** Call `reset_session` if the user says "reset," "clear context," "forget everything," or starts a "new conversation."
- **Why:** This clears TurnZero's memory of what was already injected, ensuring the **Portable AI Identity** is re-suggested immediately.

### 4. Integration
- Use `inject_block` to retrieve the full text of relevant priors before answering.
- Call `get_stats` if the user asks about TurnZero's impact or library size.
"""

_TURNZERO_AGENTS_MD_BLOCK = _TURNZERO_CLAUDE_MD_BLOCK

_TURNZERO_GEMINI_MD_BLOCK = _TURNZERO_CLAUDE_MD_BLOCK

_TURNZERO_MD_MARKER = "## TurnZero — Expert & Personal Prior Injection"
_LEGACY_TURNZERO_MD_MARKER = "## TurnZero — Expert Prior injection"


def _setup_codex_mcp(
    mcp_bin: str,
    data_dir: Path,
    force: bool,
    con: Any,
    codex_dir: Path | None = None,
) -> None:
    """Register MCP server in ~/.codex/config.toml."""
    target_dir = codex_dir or Path.home() / ".codex"
    if not target_dir.exists():
        return

    config_path = target_dir / "config.toml"
    existing = (
        config_path.read_text(encoding="utf-8") if config_path.exists() else ""
    )

    if "[mcp_servers.turnzero]" in existing and not force:
        con.print("[dim]✓ MCP server already in ~/.codex/config.toml[/dim]")
        return

    new_block = f"""
[mcp_servers.turnzero]
command = "{mcp_bin}"
env = {{ TURNZERO_DATA_DIR = "{data_dir}" }}
"""
    if "[mcp_servers.turnzero]" in existing:
        # crude overwrite
        lines = existing.splitlines(keepends=True)
        filtered = []
        skip = False
        for line in lines:
            if line.strip() == "[mcp_servers.turnzero]":
                skip = True
                continue
            if skip and line.startswith("["):
                skip = False
            if not skip:
                filtered.append(line)
        config_path.write_text(
            "".join(filtered).rstrip("\n") + new_block, encoding="utf-8"
        )
    else:
        config_path.write_text(
            existing.rstrip("\n") + "\n" + new_block.lstrip("\n"),
            encoding="utf-8",
        )

    con.print(f"[green]✓[/green] MCP server registered in {config_path}")


def _setup_cursor_mcp(
    mcp_bin: str,
    data_dir: Path,
    force: bool,
    con: Any,
) -> None:
    """Register MCP server in Cursor config."""
    import platform

    if platform.system() == "Darwin":
        config_path = Path.home() / "Library/Application Support/Cursor/User/globalStorage/saoudrizwan.claude-dev/settings/mcp_servers.json"
        # Also check the newer/alternative path if needed
        # Cursor sometimes uses different paths for different MCP plugins
    elif platform.system() == "Windows":
        config_path = Path(os.environ["APPDATA"]) / "Cursor/User/globalStorage/saoudrizwan.claude-dev/settings/mcp_servers.json"
    else:
        return

    # If the specific plugin path doesn't exist, we skip for now as we don't want to 
    # guess which MCP plugin the user is using in Cursor (though saoudrizwan.claude-dev is common)
    if not config_path.parent.exists():
        return

    config: dict[str, Any] = {}
    if config_path.exists():
        with contextlib.suppress(json.JSONDecodeError):
            config = json.loads(config_path.read_text(encoding="utf-8"))

    mcp_entry = {
        "command": mcp_bin,
        "args": [],
        "env": {"TURNZERO_DATA_DIR": str(data_dir)},
        "disabled": False
    }

    mcp_servers = config.setdefault("mcpServers", {})
    if "turnzero" not in mcp_servers or force:
        mcp_servers["turnzero"] = mcp_entry
        config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
        con.print(f"[green]✓[/green] MCP server registered in Cursor ({config_path.name})")
    else:
        con.print("[dim]✓ MCP server already in Cursor[/dim]")


def _setup_claude_desktop_mcp(
    mcp_bin: str,
    data_dir: Path,
    force: bool,
    con: Any,
) -> None:
    """Register MCP server in Claude Desktop config."""
    import platform

    if platform.system() == "Darwin":
        config_path = Path.home() / "Library/Application Support/Claude/claude_desktop_config.json"
    elif platform.system() == "Windows":
        config_path = Path(os.environ["APPDATA"]) / "Claude/claude_desktop_config.json"
    else:
        return

    if not config_path.parent.exists():
        return

    config: dict[str, Any] = {}
    if config_path.exists():
        with contextlib.suppress(json.JSONDecodeError):
            config = json.loads(config_path.read_text(encoding="utf-8"))

    mcp_entry = {
        "command": mcp_bin,
        "args": [],
        "env": {"TURNZERO_DATA_DIR": str(data_dir)},
    }

    mcp_servers = config.setdefault("mcpServers", {})
    if "turnzero" not in mcp_servers or force:
        mcp_servers["turnzero"] = mcp_entry
        config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
        con.print(f"[green]✓[/green] MCP server registered in Claude Desktop ({config_path.name})")
    else:
        con.print("[dim]✓ MCP server already in Claude Desktop[/dim]")


def _setup_gemini_mcp(
    mcp_bin: str,
    data_dir: Path,
    force: bool,
    con: Any,
) -> None:
    """Register MCP server in Gemini CLI config."""
    config_path = Path.home() / ".gemini" / "settings.json"

    # If ~/.gemini doesn't exist, the user likely hasn't used Gemini CLI
    if not config_path.parent.exists():
        return

    config: dict[str, Any] = {}
    if config_path.exists():
        with contextlib.suppress(json.JSONDecodeError):
            config = json.loads(config_path.read_text(encoding="utf-8"))

    mcp_entry = {
        "command": mcp_bin,
        "args": [],
        "env": {"TURNZERO_DATA_DIR": str(data_dir)},
    }

    mcp_servers = config.setdefault("mcpServers", {})
    if "turnzero" not in mcp_servers or force:
        mcp_servers["turnzero"] = mcp_entry
        config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
        con.print(
            f"[green]✓[/green] MCP server registered in Gemini CLI ({config_path.name})"
        )
    else:
        con.print("[dim]✓ MCP server already in Gemini CLI[/dim]")


def _setup_claude_md(force: bool, con: Any, claude_dir: Path | None = None) -> None:
    """Write TurnZero instruction block to ~/.claude/CLAUDE.md (global Claude Code rules)."""
    target_dir = claude_dir or Path.home() / ".claude"
    if not target_dir.exists():
        return

    md_path = target_dir / "CLAUDE.md"
    existing = md_path.read_text(encoding="utf-8") if md_path.exists() else ""

    if _TURNZERO_MD_MARKER in existing or _LEGACY_TURNZERO_MD_MARKER in existing:
        if not force and _TURNZERO_MD_MARKER in existing:
            con.print(f"[dim]✓ TurnZero rule already in {md_path.name}[/dim]")
            return
        # Remove old/legacy block before rewriting
        lines = existing.splitlines(keepends=True)
        filtered: list[str] = []
        skip = False
        for line in lines:
            if _TURNZERO_MD_MARKER in line or _LEGACY_TURNZERO_MD_MARKER in line:
                skip = True
            elif skip and line.startswith("## ") and _TURNZERO_MD_MARKER not in line and _LEGACY_TURNZERO_MD_MARKER not in line:
                skip = False
            if not skip:
                filtered.append(line)
        existing = "".join(filtered).rstrip("\n")

    md_path.write_text(existing + _TURNZERO_CLAUDE_MD_BLOCK, encoding="utf-8")
    con.print(f"[green]✓[/green] TurnZero rule written to {md_path}")


def _setup_codex_agents_md(
    force: bool, con: Any, codex_dir: Path | None = None
) -> None:
    """Write instructions to ~/.codex/agents.md for Codex support."""
    target_dir = codex_dir or Path.home() / ".codex"
    if not target_dir.exists():
        return

    md_path = target_dir / "AGENTS.md"
    existing = md_path.read_text(encoding="utf-8") if md_path.exists() else ""

    if _TURNZERO_MD_MARKER in existing or _LEGACY_TURNZERO_MD_MARKER in existing:
        if not force and _TURNZERO_MD_MARKER in existing:
            con.print(f"[dim]✓ TurnZero rule already in {md_path.name}[/dim]")
            return
        # Remove old block before rewriting
        lines = existing.splitlines(keepends=True)
        filtered: list[str] = []
        skip = False
        for line in lines:
            if _TURNZERO_MD_MARKER in line or _LEGACY_TURNZERO_MD_MARKER in line:
                skip = True
            elif skip and line.startswith("## ") and _TURNZERO_MD_MARKER not in line and _LEGACY_TURNZERO_MD_MARKER not in line:
                skip = False
            if not skip:
                filtered.append(line)
        existing = "".join(filtered).rstrip("\n")

    md_path.write_text(existing + _TURNZERO_AGENTS_MD_BLOCK, encoding="utf-8")
    con.print(f"[green]✓[/green] TurnZero rule written to {md_path}")


def _setup_gemini_md(force: bool, con: Any, gemini_dir: Path | None = None) -> None:
    """Write TurnZero instruction block to ~/.gemini/GEMINI.md (global Gemini CLI rules)."""
    target_dir = gemini_dir or Path.home() / ".gemini"
    if not target_dir.exists():
        return

    md_path = target_dir / "GEMINI.md"
    existing = md_path.read_text(encoding="utf-8") if md_path.exists() else ""

    if _TURNZERO_MD_MARKER in existing or _LEGACY_TURNZERO_MD_MARKER in existing:
        if not force and _TURNZERO_MD_MARKER in existing:
            con.print(f"[dim]✓ TurnZero rule already in {md_path.name}[/dim]")
            return
        # Remove old/legacy block before rewriting
        lines = existing.splitlines(keepends=True)
        filtered: list[str] = []
        skip = False
        for line in lines:
            if _TURNZERO_MD_MARKER in line or _LEGACY_TURNZERO_MD_MARKER in line:
                skip = True
            elif skip and line.startswith("## ") and _TURNZERO_MD_MARKER not in line and _LEGACY_TURNZERO_MD_MARKER not in line:
                skip = False
            if not skip:
                filtered.append(line)
        existing = "".join(filtered).rstrip("\n")

    md_path.write_text(existing + _TURNZERO_GEMINI_MD_BLOCK, encoding="utf-8")
    con.print(f"[green]✓[/green] TurnZero rule written to {md_path}")


def setup(
    data_dir: Path = typer.Option(
        None,
        "--data-dir",
        "-d",
        help="Where to store blocks and index. Default: ~/.turnzero",
    ),
    force: bool = typer.Option(
        False, "--force", "-f", help="Overwrite existing MCP config."
    ),
    with_hook: bool = typer.Option(
        False,
        "--with-hook",
        help="Also install the Claude Code UserPromptSubmit hook for guaranteed injection regardless of model behaviour.",
    ),
    openai_key: str = typer.Option(
        None,
        "--openai-key",
        help="OpenAI API key for cloud embedding fallback (stored at ~/.turnzero/openai_key).",
        envvar="OPENAI_API_KEY",
    ),
    interactive: bool = typer.Option(
        True,
        "--interactive/--no-interactive",
        help="Whether to prompt for actions like pulling models.",
    ),
) -> None:
    """One-command setup: register MCP server and build index.

    Registers the TurnZero MCP server globally. Any MCP-compatible AI client
    (Claude Code, Cursor, Claude Desktop) will automatically call
    list_suggested_blocks on Turn 0 and inject Expert Priors.

    Use --with-hook to also install the Claude Code UserPromptSubmit hook
    for guaranteed injection regardless of model behaviour.
    """
    import time

    import httpx

    claude_dir = Path.home() / ".claude"
    claude_dir.mkdir(exist_ok=True)

    resolved = (data_dir or Path.home() / ".turnzero").expanduser().resolve()

    console.print("\n[bold]TurnZero Setup[/bold]\n")
    console.print(f"Data directory: [cyan]{resolved}[/cyan]\n")

    # Persist OpenAI key if provided
    if openai_key:
        key_file = resolved / "openai_key"
        resolved.mkdir(parents=True, exist_ok=True)
        key_file.write_text(openai_key.strip(), encoding="utf-8")
        key_file.chmod(0o600)
        os.environ["OPENAI_API_KEY"] = openai_key.strip()
        console.print("[green]✓[/green] OpenAI API key saved\n")
    elif (resolved / "openai_key").exists():
        os.environ["OPENAI_API_KEY"] = (
            (resolved / "openai_key").read_text().strip()
        )
        console.print("[dim]✓ OpenAI API key loaded from previous setup[/dim]\n")

    # ── 1. Copy blocks ────────────────────────────────────────────────────
    # In refactored structure, turnzero/cli/setup.py is .
    # turnzero/ is .parent
    # turnzero/data/blocks is .parent / data / blocks
    pkg_blocks = Path(__file__).parent.parent / "data" / "blocks"
    # Repo blocks is .parent.parent.parent / data / blocks
    repo_blocks = Path(__file__).parent.parent.parent / "data" / "blocks"
    source_blocks = pkg_blocks if pkg_blocks.exists() else repo_blocks
    dest_blocks = resolved / "blocks"

    if source_blocks.exists():
        if not dest_blocks.exists() or force:
            if dest_blocks.exists():
                shutil.rmtree(dest_blocks)
            shutil.copytree(source_blocks, dest_blocks)
            n = len(list(dest_blocks.rglob("*.yaml")))
            console.print(f"[green]✓[/green] Copied {n} blocks → {dest_blocks}")
        else:
            n = len(list(dest_blocks.rglob("*.yaml")))
            console.print(f"[dim]✓ {n} blocks already at {dest_blocks}[/dim]")
    else:
        console.print(
            "[yellow]⚠[/yellow]  Source blocks not found — "
            "copy your blocks/ directory to [cyan]{dest_blocks}[/cyan] manually."
        )

    # ── 2. Check embedding backend ────────────────────────────────────────
    console.print()
    ollama_ok = False

    # Check if ollama is in PATH
    ollama_path = shutil.which("ollama")
    if not ollama_path:
        console.print("[red]✗[/red] ollama not found in PATH.")
        console.print(
            "  Required for local-only privacy. Install from [cyan]https://ollama.com[/cyan]\n"
        )
    else:
        host = os.environ.get("OLLAMA_HOST", "http://localhost:11434").rstrip("/")
        try:
            # Check if server is running
            with httpx.Client(timeout=2.0) as client:
                client.get(f"{host}/api/tags")

            # Server is running, check for model
            result = subprocess.run(
                ["ollama", "list"],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            )
            if "nomic-embed-text" in result.stdout:
                console.print(
                    "[green]✓[/green] Embedding backend: ollama (nomic-embed-text)"
                )
                ollama_ok = True
            elif force or (
                interactive
                and typer.confirm(
                    "\nollama is running, but 'nomic-embed-text' model is missing. Pull it now? (approx 2GB)"
                )
            ):
                console.print("Pulling nomic-embed-text…")
                subprocess.run(["ollama", "pull", "nomic-embed-text"], check=True)
                console.print("[green]✓[/green] nomic-embed-text pulled")
                ollama_ok = True
            else:
                console.print(
                    "[yellow]⚠[/yellow] nomic-embed-text missing. Run: [cyan]ollama pull nomic-embed-text[/cyan]"
                )
        except (httpx.ConnectError, httpx.TimeoutException):
            console.print(
                "[yellow]⚠[/yellow] ollama is installed but the server is not running."
            )
            if interactive and typer.confirm("Attempt to start ollama server?"):
                console.print("Starting ollama serve in background…")
                subprocess.Popen(
                    ["ollama", "serve"],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    start_new_session=True,
                )
                console.print("Waiting for server to start…")
                for _ in range(5):
                    time.sleep(1)
                    try:
                        with httpx.Client(timeout=1.0) as client:
                            if client.get(f"{host}/api/tags").status_code == HTTP_OK:
                                break
                    except Exception:
                        pass

                # Try pulling model now
                try:
                    subprocess.run(
                        ["ollama", "pull", "nomic-embed-text"], check=True
                    )
                    console.print("[green]✓[/green] ollama started and model pulled")
                    ollama_ok = True
                except Exception:
                    console.print(
                        "[red]✗ Failed to pull model. Please run 'ollama pull nomic-embed-text' manually.[/red]"
                    )

    # Check OpenAI as fallback
    if not ollama_ok and os.environ.get("OPENAI_API_KEY"):
        console.print("[green]✓[/green] Embedding backend: OpenAI API")
        ollama_ok = True

    if not ollama_ok:
        console.print("\n[red]✗ No embedding backend available.[/red]")
        console.print(
            "  TurnZero requires either local [bold]ollama[/bold] or [bold]OpenAI[/bold] for embeddings."
        )
        console.print(
            "  Setup will continue, but you must fix this before querying."
        )

    # ── 3. Build index ────────────────────────────────────────────────────
    console.print()
    index_path = resolved / "index.jsonl"
    index_ok = False
    if ollama_ok and dest_blocks.exists():
        if not index_path.exists() or force:
            console.print("Building embedding index…")
            env = os.environ.copy()
            env["TURNZERO_DATA_DIR"] = str(resolved)
            try:
                subprocess.run(
                    [sys.executable, "-m", "turnzero", "index", "build"],
                    env=env,
                    check=True,
                )
                console.print("[green]✓[/green] Index built")
                index_ok = True
            except subprocess.CalledProcessError:
                console.print(
                    "[red]✗ Index build failed — check ollama is running[/red]"
                )
        else:
            console.print("[dim]✓ Index already exists[/dim]")
            index_ok = True
    else:
        console.print(
            "[dim]Skipping index build. Once ollama is ready, run:[/dim]\n"
            f"  [cyan]TURNZERO_DATA_DIR={resolved} turnzero index build[/cyan]"
        )

    # ── 4. Write hook script (optional) ──────────────────────────────────
    console.print()
    if with_hook:
        hook_path = claude_dir / "turnzero-hook.py"
        if not hook_path.exists() or force:
            hook_path.write_text(
                _generate_hook(sys.executable, resolved), encoding="utf-8"
            )
            hook_path.chmod(0o755)
            console.print(f"[green]✓[/green] Hook written → {hook_path}")
        else:
            console.print(
                f"[dim]✓ Hook already exists ({hook_path}) — use --force to regenerate[/dim]"
            )

        # ── 5. Register hook in ~/.claude/settings.json ───────────────────
        settings_path = claude_dir / "settings.json"
        settings: dict[str, Any] = {}
        if settings_path.exists():
            import contextlib

            with contextlib.suppress(json.JSONDecodeError):
                settings = json.loads(settings_path.read_text(encoding="utf-8"))

        hook_command = f"{sys.executable} {hook_path}"
        hook_entry = {"type": "command", "command": hook_command, "timeout": 6}
        hooks = settings.setdefault("hooks", {})
        submit_hooks = hooks.setdefault("UserPromptSubmit", [{"hooks": []}])
        hook_list = submit_hooks[0].setdefault("hooks", [])
        already = any("turnzero-hook.py" in h.get("command", "") for h in hook_list)
        if not already:
            hook_list.append(hook_entry)
            settings_path.write_text(
                json.dumps(settings, indent=2), encoding="utf-8"
            )
            console.print(f"[green]✓[/green] Hook registered in {settings_path}")
        else:
            console.print("[dim]✓ Hook already registered in settings.json[/dim]")
    else:
        console.print(
            "[dim]Hook not installed (MCP server is enough for most clients — use --with-hook for Claude Code guarantee)[/dim]"
        )

    # ── 6. Register MCP in ~/.claude.json ────────────────────────────────
    claude_json = Path.home() / ".claude.json"
    cfg: dict[str, Any] = {}
    if claude_json.exists():
        import contextlib

        with contextlib.suppress(json.JSONDecodeError):
            cfg = json.loads(claude_json.read_text(encoding="utf-8"))

    mcp_bin = str(Path(sys.executable).parent / "turnzero-mcp")
    mcp_entry = {
        "type": "stdio",
        "command": mcp_bin,
        "env": {"TURNZERO_DATA_DIR": str(resolved)},
    }
    servers = cfg.setdefault("mcpServers", {})
    if "turnzero" not in servers or force:
        servers["turnzero"] = mcp_entry
        claude_json.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
        console.print(f"[green]✓[/green] MCP server registered in {claude_json}")
    else:
        console.print("[dim]✓ MCP server already registered in .claude.json[/dim]")

    # ── 6b. Register MCP in ~/.codex/config.toml (Codex CLI) ─────────────
    _setup_codex_mcp(mcp_bin, resolved, force, console)

    # ── 6c. Register MCP in Cursor ──────────────────────────────────────
    _setup_cursor_mcp(mcp_bin, resolved, force, console)

    # ── 6d. Register MCP in Claude Desktop ──────────────────────────────
    _setup_claude_desktop_mcp(mcp_bin, resolved, force, console)

    # ── 6e. Register MCP in Gemini CLI ──────────────────────────────────
    _setup_gemini_mcp(mcp_bin, resolved, force, console)

    # ── 6f. Write global instruction rules (makes AI invoke tools reliably) ─
    _setup_claude_md(force, console)
    _setup_codex_agents_md(force, console)
    _setup_gemini_md(force, console)

    # ── 7. Summary ────────────────────────────────────────────────────────
    console.print()
    if ollama_ok and index_ok:
        console.print("[bold green]✓ Setup complete![/bold green]\n")
        console.print(
            "Start a [bold]new[/bold] Claude Code session and paste this prompt to verify:\n\n"
            "  [cyan]Building a FastAPI REST API with Pydantic models and async SQLAlchemy[/cyan]\n\n"
            "TurnZero will inject Expert Priors automatically on Turn 0.\n"
            "Add [cyan]--with-hook[/cyan] for an extra guarantee on Claude Code."
        )
    else:
        console.print("[bold yellow]Partial setup complete.[/bold yellow]\n")
        console.print(
            "Once ollama is ready, re-run:\n\n"
            "  [cyan]turnzero setup --force[/cyan]"
        )


def feedback(
    prompt: str = typer.Option(
        ..., "--prompt", "-p", help="The opening prompt that was used."
    ),
    correction: str = typer.Option(
        ..., "--correction", "-c", help="The correction text (what the user clarified)."
    ),
    slug: str = typer.Option(
        None,
        "--slug",
        "-s",
        help="The slug of the block that was suggested/injected (optional).",
    ),
) -> None:
    """Log user feedback/correction when a suggestion was missed or incorrect."""

    feedback_data = {
        "timestamp": int(time.time()),
        "prompt": prompt,
        "correction": correction,
        "slug": slug,
    }

    feedback_file = _data_dir() / "feedback.jsonl"
    _data_dir().mkdir(parents=True, exist_ok=True)

    with feedback_file.open("a", encoding="utf-8") as f:
        f.write(json.dumps(feedback_data) + "\n")

    console.print(f"[green]✓ Feedback logged to {feedback_file}[/green]")
    console.print(
        "[dim]This data will be used to improve future Expert Prior extractions.[/dim]"
    )


def autolearn(
    sessions_dir: Path = typer.Option(
        None, "--sessions-dir", help="Single directory to scan for sessions."
    ),
    force: bool = typer.Option(
        False, "--force", help="Re-scan already processed sessions."
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Don't extract, just show what would be scanned."
    ),
    model: str = typer.Option("llama3.2", "--model", help="LLM to use for extraction."),
) -> None:
    """Scan local AI sessions and automatically harvest Expert Prior candidates."""
    from turnzero.harvest import scan_new_sessions

    data_dir = _data_dir()
    processed_file = data_dir / "processed_sessions.txt"

    console.print("\n[bold]TurnZero Autolearn[/bold]\n")

    to_scan = scan_new_sessions(
        processed_file if not force else Path("/dev/null"),
        sessions_dir=sessions_dir,
    )

    if not to_scan:
        console.print("[dim]No new sessions found.[/dim]")
        return

    console.print(f"Found {len(to_scan)} session(s) to scan.")

    if dry_run:
        for f in to_scan:
            console.print(f"  • {f}")
        return

    # Extraction loop would go here, calling harvest logic
    console.print(
        "\n[yellow]Autolearn in progress...[/yellow] (this uses local LLM)"
    )
    # ... logic from turnzero/harvest.py or similar ...
    console.print("\n[green]✓ Done. Run 'turnzero review' to see candidates.[/green]")


@source_app.command("list")
def source_list() -> None:
    """List available Expert Prior sources and their status."""
    from turnzero.config import load_config

    cfg = load_config(_data_dir())
    console.print("\n[bold]Expert Prior Sources[/bold]\n")
    for tier, enabled in cfg["sources"].items():
        status = "[green]enabled[/green]" if enabled else "[dim]disabled[/dim]"
        console.print(f"  • [bold]{tier:<12}[/bold] {status}")
    console.print()


@source_app.command("enable")
def source_enable(
    tier: str = typer.Argument(..., help="Tier to enable (local/community/team).")
) -> None:
    """Enable a specific Expert Prior source."""
    from turnzero.config import load_config, save_config

    if tier not in ("local", "community", "team"):
        err_console.print(f"[red]Invalid tier: {tier}[/red]")
        raise typer.Exit(1)

    cfg = load_config(_data_dir())
    cfg["sources"][tier] = True
    save_config(_data_dir(), cfg)
    console.print(f"[green]✓ Source '[bold]{tier}[/bold]' enabled.[/green]")


@source_app.command("disable")
def source_disable(
    tier: str = typer.Argument(..., help="Tier to disable (local/community/team).")
) -> None:
    """Disable a specific Expert Prior source."""
    from turnzero.config import load_config, save_config

    if tier == "local":
        err_console.print("[red]Cannot disable 'local' source.[/red]")
        raise typer.Exit(1)

    cfg = load_config(_data_dir())
    cfg["sources"][tier] = False
    save_config(_data_dir(), cfg)
    console.print(f"[dim]✓ Source '[bold]{tier}[/bold]' disabled.[/dim]")
